var data = [
    {
        Id: 1,
        stage: 0,
        workflowCode: "PM",
        stepTitle: "PM Request Initiator",
        assignedTo: "Workflow Engine",
        assignedOn: "N/A",
        comments: "Initialized by Workflow Engine",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "25-11-2022",
        completedBy: "Workflow Engine"
    },
    {
        Id: 2,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Rep",
        assignedTo: "Hafiz Arshad Ali Shakoor",
        assignedOn: "25-11-2022",
        comments: "task done by hafiz arshad",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "28-12-2022",
        completedBy: "Hafiz Arshad Ali Shakoor"
    },
    {
        Id: 3,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Head",
        assignedTo: "Umair Mahmood",
        assignedOn: "28-12-2022",
        comments: "this task needs to be revised",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "30-12-2022",
        completedBy: "Umair Mahmood"
    },
    {
        Id: 4,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Rep",
        assignedTo: "Hafiz Arshad Ali Shakoor",
        assignedOn: "30-12-2022",
        comments: "task revised once",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "30-12-2022",
        completedBy: "Hafiz Arshad Ali Shakoor"
    },
    {
        Id: 5,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Head",
        assignedTo: "Umair Mahmood",
        assignedOn: "30-12-2022",
        comments: "task needs to be revised again to check the history diagram",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "30-12-2022",
        completedBy: "Umair Mahmood"
    },
    {
        Id: 6,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Rep",
        assignedTo: "Hafiz Arshad Ali Shakoor",
        assignedOn: "30-12-2022",
        comments: "twice revised",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "30-12-2022",
        completedBy: "Hafiz Arshad Ali Shakoor"
    },
    {
        Id: 7,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Head",
        assignedTo: "Umair Mahmood",
        assignedOn: "30-12-2022",
        comments: "task needs to be performed by another department, so please perform again, I'm revising it",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "30-12-2022",
        completedBy: "Umair Mahmood"
    },
    {
        Id: 8,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Rep",
        assignedTo: "Syed Asif Manazir",
        assignedOn: "30-12-2022",
        comments: "task performed by Syed Asif Manzir",
        status: "done",
        isDone: 1,
        icon: "check_circle",
        completedOn: "30-12-2022",
        completedBy: "Syed Asif Manazir"
    },
    {
        Id: 9,
        stage: 1,
        workflowCode: "PM",
        stepTitle: "PM Maint. Head",
        assignedTo: "Umair Mahmood",
        assignedOn: "30-12-2022",
        comments: "-",
        status: "pending",
        isDone: 0,
        icon: "info",
        completedOn: "N/A",
        completedBy: null
    }
]